kind: pipeline
type: kubernetes
name: guacamole-client-server-arm

platform:
  os: linux
  arch: arm

steps:
- name: clone-google-guacamole-client
  image: drone/git
  commands: 
  - git clone -b 'staging/1.2.0' --single-branch https://github.com/apache/guacamole-client

- name: build-guacamole-client
  image: arm32v7/maven:3-jdk-8
  commands:
  - mkdir -p client-dist/bin
  - guacamole-client/guacamole-docker/bin/build-guacamole.sh guacamole-client/ $(pwd)/client-dist/
  - mkdir -p $(pwd)/client-dist/header
  - tar -xzf guacamole-client/extensions/guacamole-auth-header/target/*.tar.gz -C $(pwd)/client-dist/header --wildcards --no-anchored --no-wildcards-match-slash --strip-components=1 *.jar
  - cp guacamole-client/guacamole-docker/bin/start.sh client-dist/bin/start.sh
  - cp guacamole-client/guacamole-docker/bin/initdb.sh client-dist/bin/initdb.sh

- name: publish-guacamole-client
  image: registry.artificialcreature.com/drone-plugins/kaniko:latest
  settings:
    registry: registry.artificialcreature.com
    repo: apache/guacamole-client
    tags: latest
    log: info
    dockerfile: Dockerfile-client

- name: clone-google-guacamole-server
  image: drone/git
  commands:
  - git clone -b 'staging/1.2.0' --single-branch https://github.com/apache/guacamole-server

- name: build-guacamole-server
  image: arm32v7/ubuntu:18.04
  commands:
  - apt update
  - apt install -y autoconf automake gcc make libossp-uuid-dev libpango1.0-dev libpulse-dev libssh2-1-dev libssl-dev libtelnet-dev libtool libvncserver-dev libwebsockets-dev libwebp-dev libfreerdp-dev libcairo2-dev libjpeg-turbo8-dev libavcodec-dev libavutil-dev libswscale-dev libpng-dev
  - mkdir server-dist
  - guacamole-server/src/guacd-docker/bin/build-guacd.sh guacamole-server/ $(pwd)/server-dist/
  - guacamole-server/src/guacd-docker/bin/list-dependencies.sh $(pwd)/server-dist/sbin/guacd server-dist/lib/libguac-client-*.so $(pwd)/server-dist/lib/freerdp/guac*.so > $(pwd)/server-dist/DEPENDENCIES
  - cp guacamole-server/src/guacd-docker/bin/link-freerdp-plugins.sh server-dist/bin/link-freerdp-plugins.sh
  
- name: publish-guacamole-server
  image: registry.artificialcreature.com/drone-plugins/kaniko:latest
  settings:
    registry: registry.artificialcreature.com
    repo: apache/guacamole-server
    tags: latest
    log: info
    dockerfile: Dockerfile-server